//! Catálogo de regras. As chaves seguem as do SonarJS (referência), mas os textos são
//! nossos: por que é um problema, como corrigir e um exemplo antes/depois.

use serde::Serialize;

/// Tipo do problema, como no SonarLint.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum Kind {
    /// Comportamento errado ou provável erro em tempo de execução.
    Bug,
    /// Falha de segurança explorável.
    Vulnerability,
    /// Código sensível que precisa de revisão humana.
    SecurityHotspot,
    /// Dificulta manter e evoluir o código.
    CodeSmell,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Severity {
    Info,
    Minor,
    Major,
    Critical,
    Blocker,
}

/// Linguagens em que a regra roda.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Scope {
    /// JavaScript e TypeScript.
    Js,
    /// Só TypeScript.
    Ts,
    /// Qualquer linguagem com comentários reconhecidos.
    Any,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Rule {
    /// Chave (a do SonarJS equivalente), ex.: `S3776`.
    pub key: &'static str,
    pub name: &'static str,
    pub kind: Kind,
    pub severity: Severity,
    pub scope: Scope,
    /// Esforço estimado para corrigir, em minutos (dívida técnica).
    pub debt_minutes: u32,
    pub tags: &'static [&'static str],
    /// Por que é um problema.
    pub why: &'static str,
    /// Como corrigir.
    pub fix: &'static str,
    pub noncompliant: &'static str,
    pub compliant: &'static str,
}

pub fn rules() -> &'static [Rule] {
    RULES
}

pub fn rule(key: &str) -> Option<&'static Rule> {
    RULES.iter().find(|r| r.key == key)
}

use Kind::*;
use Scope::*;
use Severity::*;

static RULES: &[Rule] = &[
    Rule {
        key: "S3776",
        name: "Funções não devem ser complexas demais de entender",
        kind: CodeSmell,
        severity: Critical,
        scope: Js,
        debt_minutes: 10,
        tags: &["brain-overload"],
        why: "A complexidade cognitiva mede o esforço para entender o fluxo: cada desvio (if, laço, catch, ternário, sequência de && e ||) soma um ponto, e somam mais quando estão aninhados. Acima de 15, quem lê precisa guardar muitos caminhos ao mesmo tempo — é onde os bugs se escondem e onde mudanças quebram coisas sem querer.",
        fix: "Extraia trechos em funções com nomes que expliquem a intenção, troque aninhamento por retornos antecipados (guard clauses) e substitua cadeias de if por tabelas (objetos/Map) quando possível.",
        noncompliant: "function preco(p) {\n  if (p) {\n    if (p.ativo) {\n      for (const i of p.itens) {\n        if (i.desconto && !i.brinde) { /* ... */ }\n      }\n    }\n  }\n}",
        compliant: "function preco(p) {\n  if (!p?.ativo) return 0;\n  return p.itens.filter(temDesconto).reduce(somar, 0);\n}",
    },
    Rule {
        key: "S1186",
        name: "Funções não devem estar vazias",
        kind: CodeSmell,
        severity: Critical,
        scope: Js,
        debt_minutes: 5,
        tags: &["suspicious"],
        why: "Uma função vazia não diz se foi esquecida, se ainda falta implementar ou se 'não fazer nada' é o comportamento certo. Quem lê não tem como saber.",
        fix: "Implemente a função, lance um erro (`throw new Error(\"não implementado\")`) ou deixe um comentário explicando por que ela não faz nada.",
        noncompliant: "function aoFechar() {}",
        compliant: "function aoFechar() {\n  // Nada a liberar: a conexão é fechada pelo pool.\n}",
    },
    Rule {
        key: "S108",
        name: "Blocos de código não devem ficar vazios",
        kind: CodeSmell,
        severity: Major,
        scope: Js,
        debt_minutes: 5,
        tags: &["suspicious"],
        why: "Um bloco vazio em if, else, laço ou finally quase sempre é código esquecido ou um resto de refatoração.",
        fix: "Remova o bloco (e a condição, se ela não tiver efeito) ou coloque o código que faltava. Se for intencional, explique num comentário.",
        noncompliant: "if (pronto) {\n} else {\n  iniciar();\n}",
        compliant: "if (!pronto) {\n  iniciar();\n}",
    },
    Rule {
        key: "S2486",
        name: "Exceções não devem ser ignoradas",
        kind: CodeSmell,
        severity: Minor,
        scope: Js,
        debt_minutes: 15,
        tags: &["error-handling"],
        why: "Um catch vazio engole o erro: o programa segue num estado inconsistente e ninguém fica sabendo o que deu errado, o que torna a falha muito difícil de investigar.",
        fix: "Trate o erro (tente de novo, use um valor padrão, avise o usuário), registre-o, ou propague com `throw`. Se ignorar for mesmo o certo, diga por quê num comentário.",
        noncompliant: "try {\n  salvar();\n} catch (e) {}",
        compliant: "try {\n  salvar();\n} catch (e) {\n  log.error(\"falha ao salvar\", e);\n  throw e;\n}",
    },
    Rule {
        key: "S1440",
        name: "Use === e !== em vez de == e !=",
        kind: CodeSmell,
        severity: Major,
        scope: Js,
        debt_minutes: 1,
        tags: &["suspicious"],
        why: "`==` converte os tipos antes de comparar, com regras pouco intuitivas: `0 == \"\"`, `\"1\" == 1` e `[] == false` são todos verdadeiros. Isso esconde bugs.",
        fix: "Use `===`/`!==`, que comparam tipo e valor. (`== null` fica de fora: é o jeito idiomático de testar null e undefined juntos.)",
        noncompliant: "if (idade == \"18\") { }",
        compliant: "if (idade === 18) { }",
    },
    Rule {
        key: "S1525",
        name: "Remova instruções `debugger`",
        kind: CodeSmell,
        severity: Major,
        scope: Js,
        debt_minutes: 1,
        tags: &["user-experience"],
        why: "`debugger` pausa a execução quando as ferramentas de desenvolvedor estão abertas. Esquecido no código, trava o fluxo de quem usa e expõe detalhes internos.",
        fix: "Apague a instrução; use pontos de parada do editor ou do navegador.",
        noncompliant: "function calcular() {\n  debugger;\n  return total;\n}",
        compliant: "function calcular() {\n  return total;\n}",
    },
    Rule {
        key: "S106",
        name: "Não deixe `console.log` no código",
        kind: CodeSmell,
        severity: Minor,
        scope: Js,
        debt_minutes: 1,
        tags: &["bad-practice"],
        why: "Saídas de depuração poluem o console, podem vazar dados sensíveis e não têm nível nem destino configurável.",
        fix: "Remova a chamada ou troque por um logger com níveis (debug/info/warn/error).",
        noncompliant: "console.log(\"usuário\", usuario);",
        compliant: "logger.debug(\"usuário carregado\", { id: usuario.id });",
    },
    Rule {
        key: "S1135",
        name: "Acompanhe os comentários TODO",
        kind: CodeSmell,
        severity: Info,
        scope: Any,
        debt_minutes: 0,
        tags: &["cwe"],
        why: "TODO marca trabalho pendente. Espalhados pelo código, eles somem da vista e viram dívida esquecida.",
        fix: "Resolva o pendente ou transforme em tarefa no quadro (Tarefas), deixando o link no comentário.",
        noncompliant: "// TODO validar o CPF",
        compliant: "validarCpf(cpf); // ou: tarefa validar-cpf no quadro",
    },
    Rule {
        key: "S1134",
        name: "Resolva os comentários FIXME",
        kind: CodeSmell,
        severity: Major,
        scope: Any,
        debt_minutes: 0,
        tags: &["cwe"],
        why: "FIXME sinaliza um defeito conhecido e não corrigido — é um bug documentado esperando para acontecer.",
        fix: "Corrija o defeito descrito e apague o comentário.",
        noncompliant: "// FIXME estoura com lista vazia",
        compliant: "if (lista.length === 0) return [];",
    },
    Rule {
        key: "S3358",
        name: "Ternários não devem ser aninhados",
        kind: CodeSmell,
        severity: Major,
        scope: Js,
        debt_minutes: 5,
        tags: &["confusing"],
        why: "Ternários dentro de ternários obrigam a ler a expressão várias vezes para entender qual valor vence em cada caso.",
        fix: "Use if/else, um `switch` ou uma tabela de valores.",
        noncompliant: "const cor = erro ? \"vermelho\" : aviso ? \"amarelo\" : \"verde\";",
        compliant: "function cor() {\n  if (erro) return \"vermelho\";\n  if (aviso) return \"amarelo\";\n  return \"verde\";\n}",
    },
    Rule {
        key: "S107",
        name: "Funções não devem ter parâmetros demais",
        kind: CodeSmell,
        severity: Major,
        scope: Js,
        debt_minutes: 20,
        tags: &["brain-overload"],
        why: "Mais de 7 parâmetros é difícil de chamar na ordem certa e geralmente indica que a função faz coisas demais.",
        fix: "Agrupe os parâmetros num objeto (com tipo) ou divida a função.",
        noncompliant: "function criar(nome, email, idade, rua, numero, cidade, uf, cep) { }",
        compliant: "function criar(pessoa: Pessoa, endereco: Endereco) { }",
    },
    Rule {
        key: "S134",
        name: "Controle de fluxo não deve ser aninhado fundo demais",
        kind: CodeSmell,
        severity: Critical,
        scope: Js,
        debt_minutes: 10,
        tags: &["brain-overload"],
        why: "Mais de 4 níveis de if/for/while/switch/try um dentro do outro é o 'código flecha': difícil de ler, testar e mudar.",
        fix: "Inverta condições com retornos antecipados e extraia os níveis internos para funções.",
        noncompliant: "if (a) {\n  for (const x of xs) {\n    if (b) {\n      while (c) {\n        if (d) { }\n      }\n    }\n  }\n}",
        compliant: "if (!a) return;\nfor (const x of xs) processar(x);",
    },
    Rule {
        key: "S4204",
        name: "Evite o tipo `any`",
        kind: CodeSmell,
        severity: Major,
        scope: Ts,
        debt_minutes: 5,
        tags: &["typescript"],
        why: "`any` desliga a verificação de tipos: o compilador aceita qualquer uso, e o erro só aparece em produção.",
        fix: "Declare o tipo real. Se não souber, use `unknown` e estreite com verificações (`typeof`, `in`, validação).",
        noncompliant: "function ler(dados: any) {\n  return dados.nome;\n}",
        compliant: "function ler(dados: unknown) {\n  if (typeof dados === \"object\" && dados && \"nome\" in dados) return dados.nome;\n}",
    },
    Rule {
        key: "S2966",
        name: "Evite a asserção de não-nulo (`!`)",
        kind: CodeSmell,
        severity: Minor,
        scope: Ts,
        debt_minutes: 5,
        tags: &["typescript", "bad-practice"],
        why: "O `!` diz ao compilador 'confie em mim, não é null'. Se a suposição estiver errada, o erro vira um `TypeError` em tempo de execução, sem aviso nenhum.",
        fix: "Trate o caso nulo: encadeamento opcional (`?.`), valor padrão (`??`) ou uma verificação explícita.",
        noncompliant: "const nome = usuario!.nome;",
        compliant: "const nome = usuario?.nome ?? \"anônimo\";",
    },
    Rule {
        key: "S131",
        name: "`switch` deve ter `default`",
        kind: CodeSmell,
        severity: Critical,
        scope: Js,
        debt_minutes: 5,
        tags: &["cert"],
        why: "Sem `default`, valores inesperados passam em silêncio. Deixar explícito o que acontece com eles evita surpresas quando um novo caso surge.",
        fix: "Adicione `default`: trate o caso, lance um erro, ou comente por que nada precisa ser feito. Em TypeScript, um switch só com casos de string fica de fora: costuma cobrir uma união, e o compilador verifica se falta algum caso.",
        noncompliant: "switch (status) {\n  case \"ok\": aprovar(); break;\n}",
        compliant: "switch (status) {\n  case \"ok\": aprovar(); break;\n  default: throw new Error(`status desconhecido: ${status}`);\n}",
    },
    Rule {
        key: "S3923",
        name: "Ramos de uma condição não devem ser idênticos",
        kind: Bug,
        severity: Major,
        scope: Js,
        debt_minutes: 15,
        tags: &[],
        why: "Se if e else (ou os dois lados de um ternário) fazem exatamente a mesma coisa, a condição não tem efeito — quase sempre é um erro de copiar e colar.",
        fix: "Corrija o ramo que deveria ser diferente ou remova a condição.",
        noncompliant: "const taxa = vip ? 0.1 : 0.1;",
        compliant: "const taxa = vip ? 0.05 : 0.1;",
    },
    Rule {
        key: "S1871",
        name: "Ramos de um if/else if não devem repetir o mesmo código",
        kind: CodeSmell,
        severity: Major,
        scope: Js,
        debt_minutes: 10,
        tags: &["design", "suspicious"],
        why: "Dois ramos com o mesmo corpo em uma cadeia de if/else if indicam cópia por engano ou condições que deveriam estar juntas.",
        fix: "Junte as condições com `||` ou corrija o ramo copiado.",
        noncompliant: "if (a) { salvar(); }\nelse if (b) { avisar(); }\nelse if (c) { salvar(); }",
        compliant: "if (a || c) { salvar(); }\nelse if (b) { avisar(); }",
    },
    Rule {
        key: "S1764",
        name: "Os dois lados de um operador não devem ser iguais",
        kind: Bug,
        severity: Major,
        scope: Js,
        debt_minutes: 2,
        tags: &["suspicious"],
        why: "`x === x`, `a && a` ou `y - y` têm resultado fixo (ou testam NaN de um jeito obscuro): é quase sempre um erro de digitação.",
        fix: "Corrija o operando que deveria ser outro. Para testar NaN, use `Number.isNaN(x)`.",
        noncompliant: "if (a.id === a.id) { }",
        compliant: "if (a.id === b.id) { }",
    },
    Rule {
        key: "S1143",
        name: "Não use return, throw, break ou continue dentro de `finally`",
        kind: Bug,
        severity: Critical,
        scope: Js,
        debt_minutes: 20,
        tags: &["error-handling"],
        why: "Um salto dentro de `finally` descarta a exceção ou o retorno que estava em andamento: o erro some sem deixar rastro.",
        fix: "Deixe o `finally` só para liberar recursos e mova o salto para fora dele.",
        noncompliant: "try {\n  return calcular();\n} finally {\n  return 0;\n}",
        compliant: "try {\n  return calcular();\n} finally {\n  fechar();\n}",
    },
    Rule {
        key: "S2068",
        name: "Credenciais não devem ficar no código",
        kind: Vulnerability,
        severity: Blocker,
        scope: Js,
        debt_minutes: 30,
        tags: &["cwe", "owasp"],
        why: "Senhas, tokens e chaves no código vão para o git, para o bundle e para qualquer cópia do repositório. Quem lê o código ganha o acesso.",
        fix: "Leia o segredo de uma variável de ambiente ou de um cofre de segredos, e troque a credencial exposta (ela já vazou). Nomes de senha (password, senha, pwd) contam com qualquer valor; token, secret e apiKey, só com valor de cara de segredo (8+ caracteres com letras e números).",
        noncompliant: "const password = \"admin123\";",
        compliant: "const password = process.env.DB_PASSWORD;",
    },
    Rule {
        key: "S5332",
        name: "Use protocolos seguros (https) em URLs",
        kind: SecurityHotspot,
        severity: Minor,
        scope: Js,
        debt_minutes: 5,
        tags: &["cwe", "owasp"],
        why: "Dados enviados por `http://` trafegam em texto puro: qualquer um no caminho da rede pode ler ou alterar.",
        fix: "Use `https://` (localhost e 127.0.0.1 ficam de fora da regra).",
        noncompliant: "fetch(\"http://api.exemplo.com/pedidos\");",
        compliant: "fetch(\"https://api.exemplo.com/pedidos\");",
    },
    Rule {
        key: "S1523",
        name: "Não execute código dinâmico (`eval`, `new Function`)",
        kind: Vulnerability,
        severity: Critical,
        scope: Js,
        debt_minutes: 30,
        tags: &["cwe", "owasp"],
        why: "`eval` executa texto como código. Se qualquer parte desse texto vier de fora, é injeção de código direta; além disso, impede otimizações e a análise de tipos.",
        fix: "Use estruturas de dados (objetos, `JSON.parse`) ou funções explícitas no lugar do texto executado.",
        noncompliant: "const valor = eval(\"config.\" + chave);",
        compliant: "const valor = config[chave];",
    },
    Rule {
        key: "S1067",
        name: "Expressões não devem ter operadores lógicos demais",
        kind: CodeSmell,
        severity: Critical,
        scope: Js,
        debt_minutes: 5,
        tags: &["brain-overload"],
        why: "Mais de 3 operadores `&&`/`||` numa expressão é difícil de avaliar de cabeça e fácil de errar na precedência.",
        fix: "Quebre em variáveis com nomes que expliquem cada parte, ou extraia uma função.",
        noncompliant: "if (a && b || c && d && !e) { }",
        compliant: "const pronto = a && b;\nconst alternativo = c && d && !e;\nif (pronto || alternativo) { }",
    },
    Rule {
        key: "S138",
        name: "Funções não devem ser longas demais",
        kind: CodeSmell,
        severity: Major,
        scope: Js,
        debt_minutes: 20,
        tags: &["brain-overload"],
        why: "Funções com mais de 200 linhas fazem coisas demais: são difíceis de nomear, testar e reutilizar.",
        fix: "Divida em funções menores, cada uma com uma responsabilidade.",
        noncompliant: "function processar() {\n  // ... 250 linhas ...\n}",
        compliant: "function processar() {\n  const dados = carregar();\n  const validos = validar(dados);\n  return salvar(validos);\n}",
    },
    Rule {
        key: "S1121",
        name: "Atribuições não devem ficar dentro de condições",
        kind: CodeSmell,
        severity: Major,
        scope: Js,
        debt_minutes: 5,
        tags: &["suspicious"],
        why: "`if (x = y)` parece uma comparação com um `=` faltando. Mesmo quando é intencional, quem lê vai desconfiar.",
        fix: "Faça a atribuição numa linha antes e compare depois; se quis comparar, use `===`.",
        noncompliant: "if ((usuario = buscar(id))) { }",
        compliant: "const usuario = buscar(id);\nif (usuario) { }",
    },
    Rule {
        key: "S3504",
        name: "Use `let` ou `const` em vez de `var`",
        kind: CodeSmell,
        severity: Critical,
        scope: Js,
        debt_minutes: 2,
        tags: &["es2015"],
        why: "`var` tem escopo de função e é 'içado' para o topo: a variável existe antes da declaração e vaza de blocos, causando bugs sutis em laços e closures.",
        fix: "Use `const` quando o valor não muda e `let` quando muda.",
        noncompliant: "var total = 0;",
        compliant: "let total = 0;",
    },
    Rule {
        key: "S1488",
        name: "Variáveis locais não devem ser declaradas só para serem retornadas",
        kind: CodeSmell,
        severity: Minor,
        scope: Js,
        debt_minutes: 2,
        tags: &["clumsy"],
        why: "Declarar uma variável e retorná-la na linha seguinte não acrescenta informação e alonga o código.",
        fix: "Retorne a expressão diretamente.",
        noncompliant: "const total = a + b;\nreturn total;",
        compliant: "return a + b;",
    },
    Rule {
        key: "S1116",
        name: "Remova pontos e vírgulas sobrando",
        kind: CodeSmell,
        severity: Minor,
        scope: Js,
        debt_minutes: 1,
        tags: &["unused"],
        why: "Um `;` sozinho é uma instrução vazia: não faz nada e pode esconder um corpo de laço ou if que ficou faltando.",
        fix: "Apague o ponto e vírgula extra.",
        noncompliant: "fazer();;",
        compliant: "fazer();",
    },
];
